import pandas as pd


ds1 = pd.read_csv("VaccineData.csv")
ds2 = pd.read_csv("VaccineData2.csv")
ds3 = pd.read_csv("VaccineData3.csv")
ds4 = pd.read_csv("VaccineData4.csv")
ds5 = pd.read_csv("VaccineData5.csv")
ds6 = pd.read_csv("VaccineData6.csv")
ds7 = pd.read_csv("VaccineData7.csv")
ds8 = pd.read_csv("VaccineData8.csv")
ds9 = pd.read_csv("VaccineData9.csv")
ds10 = pd.read_csv("VaccineData10.csv")
ds11 = pd.read_csv("VaccineData11.csv")
ds12 = pd.read_csv("VaccineData12.csv")
ds13 = pd.read_csv("VaccineData13.csv")
ds14 = pd.read_csv("VaccineData14.csv")
ds15 = pd.read_csv("VaccineData15.csv")

dataset = pd.concat([ds1, ds2])
dataset = pd.concat([dataset, ds3])
dataset = pd.concat([dataset, ds4])
dataset = pd.concat([dataset, ds5])
dataset = pd.concat([dataset, ds6])
dataset = pd.concat([dataset, ds7])
dataset = pd.concat([dataset, ds8])
dataset = pd.concat([dataset, ds9])
dataset = pd.concat([dataset, ds10])
dataset = pd.concat([dataset, ds11])
dataset = pd.concat([dataset, ds12])
dataset = pd.concat([dataset, ds13])
dataset = pd.concat([dataset, ds14])
dataset = pd.concat([dataset, ds15])

dataset.to_csv('AllVaccineData.csv')
